print("Welcome to the tip calculator")
bill = int(input("What was your total bill?: $"))
tip = int(input("How much tip do you want to give? 10, 12, or 15?: "))
people = int(input("How many people to split the bill?: "))
split_amt = round(bill * (1 + tip / 100) / people, 2)
print(f"Each person should pay ${split_amt}")